name: Semver

on:
  pull_request:

jobs:
  semver-checks:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@34e114876b0b11c390a56381ad16ebd13914f8d5 # v4

      - uses: dtolnay/rust-toolchain@29eef336d9b2848a0b548edc03f92a220660cdb8 # stable

      - uses: Swatinem/rust-cache@e18b497796c12c097a38f9edb9d0641fb99eee32 # v2
        with:
          workspaces: ". -> target"

      - name: Install cargo-semver-checks
        run: which cargo-semver-checks || cargo install cargo-semver-checks --locked

      - name: Check semver compliance
        run: cargo semver-checks check-release --workspace
